# Generic configuration to be applied to all services
#Metrics related configurations
management.endpoint.metrics.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
#H2 configuration
spring.h2.console.enabled=true
spring.cloud.refresh.enabled=false
